# Generated by Django 3.1.4 on 2021-01-24 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('year', models.CharField(max_length=256)),
                ('runtime', models.CharField(max_length=256)),
                ('rated', models.CharField(max_length=256)),
                ('genre', models.CharField(max_length=256)),
                ('director', models.CharField(max_length=256)),
                ('actors', models.CharField(max_length=256)),
                ('plot', models.CharField(max_length=256)),
                ('language', models.CharField(max_length=256)),
                ('awards', models.CharField(max_length=256)),
                ('poster', models.CharField(max_length=256)),
                ('rotten_tomato', models.CharField(max_length=256)),
                ('imdb', models.CharField(max_length=256)),
                ('metacritic', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
