# Generated by Django 3.1.4 on 2021-01-31 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210124_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='vetos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='movies_seen',
            field=models.ManyToManyField(to='movies.Movie'),
        ),
    ]
